services:
  app:
    container_name: ntu-add-drop-automator-app-1
    build: .
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - app-network
    volumes:
      - ./logs:/app/logs
      - ./debug.log:/app/debug.log

  redis:
    container_name: ntu-add-drop-automator-redis-1
    image: redis/redis-stack:latest
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  redis-data: