services:
  app:
    container_name: ntu-add-drop-automator-app-1
    build: .
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
    networks:
      - app-network

  redis:
    container_name: ntu-add-drop-automator-redis-1
    image: redis:latest
    restart: unless-stopped
    command: redis-server --requirepass ${{ secrets.REDIS_PASSWORD }}
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: